# .github/workflows/build.yml

name: Go Build

on:
  push:
    branches:
      - master

jobs:
  build-vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Build Vue
        run: |
          cd web
          npm install
          npm run build
          mv dist ../vue-project-dist
          
  build-windows:
    needs: build-vue
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Windows
        run: |
          rm -r web
          mv golang-web web
          go build -o myapp_windows.exe

  build-linux:
    needs: build-vue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Prepare Golang
        run: |
          mkdir -p vue-project-dist
          cp -R ../vue-project-dist vue-project-dist
          cd vue-project-dist
          ls

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o myapp_macos

  build-macos:
    needs: build-vue
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build macOS
        run: |
          rm -r web
          mv golang-web web
          GOOS=darwin GOARCH=amd64 go build -o myapp_macos
